### ISSUE TITLE
Change the theme directory symlink to be relative

### ISSUE THREAD

**Issue by clemherreman** [ExtremeSensio/EasyWordpressBundle#12]
Presently, we're creating a symlink from `/web/content/themes` to `/absolute/path/to/projectroot/app/Resources/themes`.

As the symlink is absolute, hen using something like a VM or Docker (with `docker-machine`) to develop, the symlink is broken on the host, and on the IDE.

We could replace this with a relative symlink: `/web/content/themes` to `../../app/Resources/themes` (not tested ^^).

**Comment by toutma** [comment]
In the `config.yml`the path is actually: ` '%kernel.root_dir%/Resources/themes/mytheme/'`

**Comment by zalexki** [comment]
@clemherreman @toutma pretty sure we can close this issue, no ?

**Comment by toutma** [comment]
Yes
