### ISSUE TITLE
Get wp cli with composer

### ISSUE THREAD

**Issue by zalexki** [ExtremeSensio/EasyWordpressBundle#19]
I'm not sure about the state of this functionality where at the installation of the bundle we download and install wp-cli for easy implementation.
Need some digging in the scripts part of `composer.json`.

**Comment by clemherreman** [comment]
We don't. We require to have WP-cli available if you want to use this bundle.
Technically, the bundle doesn't depend on it, one could download and install Wordpress manually.

We gave a shot with @toutma, but backed off, simply because we didn't feel it was worth it.
